app/views/issue_templates/_template_pulldown.html.erb

If you change the tracker on the issue creation form, the issue template with the default settings will be displayed, but the setting values will not be displayed on the screen due to an error in JavaScript.
```
Uncaught SyntaxError: Identifier 'load_url' has already been declared
at b (jquery-3.5.1-ui-1.12.1-ujs-5.2.3.js?1613355381:2)
at Pe (jquery-3.5.1-ui-1.12.1-ujs-5.2.3.js?1613355381:2)
at s.fn.init.append (jquery-3.5.1-ui-1.12.1-ujs-5.2.3.js?1613355381:2)
at s.fn.init.<anonymous> (jquery-3.5.1-ui-1.12.1-ujs-5.2.3.js?1613355381:2)
at $ (jquery-3.5.1-ui-1.12.1-ujs-5.2.3.js?1613355381:2)
at s.fn.init.html (jquery-3.5.1-ui-1.12.1-ujs-5.2.3.js?1613355381:2)
at Object.<anonymous> (issue_templates.js?1614134447:187)
at c (jquery-3.5.1-ui-1.12.1-ujs-5.2.3.js?1613355381:2)
at Object.fireWith …
```

JavaScript error when changing tracker

---

app/controllers/global_issue_templates_controller.rb
app/controllers/global_note_templates_controller.rb
test/functional/global_issue_templates_controller_test.rb

#4:
Trackers in Global issue templates and Global note templates do arrange in position order. However, I haven't created a test because the functional test file for GlobalNoteTemplatesControllerTest doesn't exist.

Sort trackers in position order

---

config/locales/sr-YU.yml

Probably due to the i18n gem version upgrade, the sr-YU language file fails to load when Redmine starts. (in Redmine trunk)
Fixing the key will make it work correctly.
```
I18n::InvalidFilenames (Found 1 error(s).
The first 1 error(s):
/var/lib/redmine/plugins/redmine_issue_templates/config/locales/sr-YU.yml can only load translations for "sr-YU". Found translations for: [:sr].
To use the LazyLoadable backend:
1. Filenames must start with the locale.
2. An underscore must separate the locale with any optional text that follows.
3. The file must only contain translation data for the single locale.
Example:
"/config/locales/fr.yml" which contains:
fr:
dog:
chien
):
lib/redmine/i18n.rb:115:in `valid_languages'
lib/redmine/i18n.rb:141:in `find_language' …
```

Change the key in the sr-YU language file

---

app/models/note_template.rb
test/unit/note_template_test.rb

#15:
I added presence validation for NoteTemplate#tracker. This will prevent raising Internal error exception.

Add presence validation for NoteTemplate#tracker(0.3-stable)

---

app/controllers/concerns/issue_templates_common.rb
assets/javascripts/issue_templates.js

`IssuesHelper#users_for_new_issue_watchers` returns empty array when there are more than 20 project members.

show all available watchers in json generator

---

.circleci/config.yml

#40 - CircleCI "test" job mysql connection error solved by renaming mysql image environment user key `MYSQL_USER` to `MYSQL_ROOT_USER`.
There were some test failures, but I will create another issue for that later.
```
#!/bin/bash -eo pipefail
bundle exec rake ${CIRCLE_PROJECT_REPONAME}:test RAILS_ENV=test
Run options: --seed 41859
..........F
Failure:
IssueTemplatesControllerTest#test_preview_template [/home/circleci/repo/plugins/redmine_issue_templates/test/functional/issue_templates_controller_test.rb:120]:
<p>h1. Test data.</p>
.
Expected 0 to be >= 1.
rails test plugins/redmine_issue_templates/test/functional/issue_templates_controller_test.rb:116
......................F
Failure:
IssueTemplatesSettingsControllerTest#test_preview_template_setting …
```

Rename CircleCI test mysql user key

---

CHANGELOG.md
README.md

There was a lot of typos in the documentation. Tried to fix as much as possible. Reordered some chapters and moved the changelog in a separate file - the README was too long and difficult to read.

Documentation fixes

---

app/controllers/note_templates_controller.rb
app/views/note_templates/_list_note_templates.html.erb
lib/issue_templates/journals_hook.rb
spec/requests/note_templates_spec.rb

#47
Improved sort order of note templates in pop-up dialog, but RSpec testing is not working at this time. Hopefully pull request #50, an improved RSpec tests will be merged into the 0.3-stable branch first.

Improve sort order of note templates in pop-up dialog(0.3-stable)

---

app/controllers/issue_templates_controller.rb
spec/features/create_issue_spec.rb

'is_update_issue' is not used at parameter 'is_triggered_by.'
So, when parameter has key 'is_triggered_by,' `loadable_trigger?` always returns `false`, and default template is not loaded.
Instead of that, check it is 'issue_tracker_id' or not. 'issue_tracker_id' is sent when changing tracker.

load default template when tracker changed

---

app/views/global_note_templates/index.html.erb
config/locales/ja.yml

Regarding `no_note_templates_for_this_redmine`, I believe we should have prepared a string for each language. However, as there are many languages and it would be too difficult to handle, we have prepared translations only for Japanese and set the default text in English for all other languages.

Display the ja locale text when global note text templates are empty

---

app/models/global_note_template.rb
app/models/note_template.rb
spec/features/update_issue_spec.rb

Regarding note templates, we have fixed it so that when "enabled" is set to false (i.e. disabled), the template will no longer be displayed during comment editing. Previously, even when "enabled" was false, the template would still be displayed as a template.

Hide disabled (global) note templates

---

app/views/note_templates/show.html.erb
spec/features/update_template_spec.rb

When there is edit permission, the note template preview should not be displayed. Therefore, the preview is no longer shown when edit permission is present.

Removed note template preview

---

app/models/concerns/attribute_name_mapper.rb
app/models/global_issue_template.rb
app/models/global_note_template.rb
app/models/issue_template.rb
app/models/note_template.rb
app/views/global_note_templates/index.html.erb
app/views/note_templates/show.html.erb
config/locales/ja.yml
db/migrate/20230330055341_change_global_note_template_projects_table_name.rb
spec/features/issue_template_spec.rb
spec/features/update_issue_spec.rb
spec/features/update_template_spec.rb
spec/models/global_note_template_spec.rb
test/functional/global_issue_templates_controller_test.rb
test/functional/issue_templates_controller_test.rb

The global comment template and project relation were set to `dependent: :nullify`, but since the schema does not allow null values, the deletion failed. Therefore, the relation was switched to use `has_and_belongs_to_many`, making it function like `dependent: :destroy`. During this process, it was necessary to change the name of the intermediate table, so a migration was created.
---
What happend: Deleting global comment templates results in an internal error
Reproduction steps:
1. Create a global comment template (also check for available projects)
2. Change the created comment template from enabled to disabled
3. Delete the comment template
Result: An internal error occurs
---
**This PR also includes the changes made in PRs #66, #67, #69, and #70. (They have all been reviewed in their …

Fix project bound global note template deletion

---

.circleci/config.yml
spec/features/drag_and_drop_spec.rb

- Changed ci configuration to support ruby 3.1 version
- fix(add) specs
below automated tests fail only in Redmine 4.1 version because the `drag_to` method does not work correctly.
[spec/features/drag_and_drop_spec.rb](https://github.com/agileware-jp/redmine_issue_templates/commit/ca4829c4e32fcf6da2398c91633f28ee4010daed#diff-9f6ceef34373fa7c8505f9df4655f273bee3f589e8995d7ab187b59befdaa015)
Therefore, we have addressed this so that a similar test can be performed with a different implementation only for the Redmine 4.1 version.
https://github.com/agileware-jp/redmine_issue_templates/commit/ca4829c4e32fcf6da2398c91633f28ee4010daed

support Ruby 3.1

---

assets/javascripts/issue_templates.js

When changing the value of a select box via the "Enable Builtin Field support" feature, the change event is not fired.
Examples of problems caused by this:
1. when the "Enable Builtin Field support" feature is used to update the value of a category, the default person is not applied even if the default person for the category has been determined.
2. customisation of select box values in ViewCustomize plugin does not work when the "Enable Builtin Field support" feature is used to change them Example: https://github.com/onozaty/ redmine-view-customize-scripts/blob/master/examples/0008.change_custom_field_visibility_by_status/example.md
3. redmica_ui_extension plugin has added a function to make the selectbox searchable, but when changing the value of the selectbox with the "Enable Builtin …

Add a dispatchEvent that runs after the selectbox has been changed

---

Gemfile.local
README.md
spec/rails_helper.rb

To pass the tests on CI, add `headless` option as default.

Fix failed specs

---

.circleci/config.yml
app/models/global_issue_template.rb
app/models/global_note_template.rb
app/models/global_note_template_project.rb
app/models/global_note_visible_role.rb
app/models/issue_template.rb
app/models/issue_template_setting.rb
app/models/note_template.rb
app/models/note_visible_role.rb

Fixes #95.
Before Redmine trunk r22619, there was no `ApplicationRecord` class, so we dynamically determine and evaluate the class expression.
We manually confirmed that template creation and usage are possible in the following environment combinations:
- Ruby v2.7 x Redmine v4.2.11
- Ruby v3.2 x Redmine v5.1.2
- Ruby v3.2 x Redmine trunk (r22776)

Use ApplicationRecord instead of ActiveRecord::Base from trunk r22619

---

scripts/issue_templates.js
spec/features/issue_template_popup_spec.rb

Fixed an error when applying issue templates with 'Replace subject and description' enabled on trackers where the standard 'Description' field is disabled.
The steps to reproduce the issue are as follows:
1. In the tracker settings, uncheck the 'Description' option under the Standard field.
2. In the 'Template Optional Settings', enable the "Replace subject and description" option.
3. Create an issue template with an 'Issue title' for the tracker from step 1.
4. On the New Issue screen, select the tracker from step 1 and the issue template from step 3.
5. The 'Issue title' from the issue template is not applied to the 'Subject' of the new issue.
```
Environment:
Redmine version                5.1.3.stable
Ruby version                   3.2.5-p208 (2024-07-26) [aarch64-linux]
Rails version …
```

Fix 'Replace subject and description' option was not applied when core field 'description' was disabled in tracker configuration

---

app/models/concerns/issue_template_common.rb

This pull request fixes the following error that occurs in Rails 7.2 (Redmine trunk after [r22960](https://www.redmine.org/projects/redmine/repository/svn/revisions/22960)) to prepare for future releases of Redmine.
```
wrong number of arguments (given 2, expected 1) (ArgumentError) /usr/local/bundle/gems/activerecord-7.2.1 /lib/active_record/attribute_methods/serialization.rb:183:in `serialize' /path/to/redmine/plugins/redmine_issue_templates/app/models/concerns/issue_template_common.rb:46:in `block in <module:IssueTemplateCommon>'
```
This error is due to the following incompatible change in Rails 7.2.
```
Remove deprecated support to passing coder and class as second argument to serialize
```
https://edgeguides.rubyonrails.org/7_2_release_notes.html#active-record-removals
Also, a …

Fix "wrong number of arguments in serialize" error in Rails 7.2 to prepare for future releases of Redmine

---

.github/workflows/check-assets-js.yml

This pull request proposes a way to keep assets/javascripts/issue_templates.js up to date.
Currently, when we change any code in the scripts/ directory, we need to run `npm run build` command to rebuild and update the issue_templates.js.
However, as in #103 , the issue_templates.js may be merged into the master branch again while still out-of-date.
This pull request adds a workflow that checks if the issue_templates.js is up to date and tells it to build and push again if it is out of date.
I implemented this workflow by referencing [check-dist.yml of the actions/javascript-action](https://github.com/actions/javascript-action/blob/main/.github/workflows/check-dist.yml).
Below are results when tested in my own repository.
Pull request: …

Add a workflow to check if issue_templates.js is up to date

---

.circleci/config.yml

Pull request #109 is a github workflow.
This is the CircleCI version of it.

CircleCI: Add a workflow to check if issue_templates.js is up to date

---

app/views/global_issue_templates/_form.html.erb
app/views/global_issue_templates/index.html.erb
app/views/global_note_templates/_form.html.erb
app/views/issue_templates/_list_templates.html.erb
app/views/note_templates/_list_note_templates.html.erb
app/views/note_templates/index.html.erb
app/views/settings/_redmine_issue_templates.html.erb
assets/stylesheets/issue_templates.css

In Redmine 6.0, the template apply button is not displayed, making it unclickable.
This issue occurs because the `display` style for elements with the `.icon` class has changed to `inline-flex` in Redmine 6.0.
https://github.com/redmine/redmine/blob/0abf7105dab7c6558a26cdcc28c6770ad89649d0/app/assets/stylesheets/application.css#L1728
This change affects all icon-only elements in this plugin.
To resolve this, I modified to replace the `.icon` class with the existing `.icon-only` class for all icon elements.
I verified all icon-only images display correctly.
<details><summary>Results for other pages</summary>
<p>
Note (the template in the 2nd line is a global note template):
Add global template/note form:
Plugin configuration form:
</p>
</details> 
Environments:
```
Environment:
Redmine …
```

Fix missing template apply button in Redmine 6.0

---

.circleci/config.yml

No production code changes.
Current master (34537be) + empty commit failure: https://app.circleci.com/pipelines/github/agileware-jp/redmine_issue_templates/169/workflows/5bcc150f-ee57-4261-8050-094081241375
This pull-request fixes it.

ci: update agileware-jp/redmine-plugin orb version

---

spec/rails_helper.rb
spec/spec_helper.rb

This pull request addresses a test failure in rspec caused by `NoMethodError: undefined method 'fixture_path='`.
https://app.circleci.com/pipelines/github/hidakatsuya/redmine_issue_templates/3/workflows/0b7a45a5-d9c9-419f-b203-45a9cb3a67d5/jobs/22
```
NoMethodError:
undefined method `fixture_path=' for #<RSpec::Core::Configuration:0x00007fcec664f298>
```
In Rails 7.1, `TestFixture#fixture_paths=` was introduced as a replacement for `fixture_path=`, and in Rails 7.2, `fixture_path=` was removed.
https://github.com/rails/rails/pull/47675

Fix test failure caused by NoMethodError: undefined method 'fixture_path='

---

lib/issue_templates/issues_hook.rb

This PR adjusts the display order of sections in the issue list sidebar to prioritize "Custom queries" for better accessibility.
Custom queries are generally used more frequently than issue template links. Placing the custom queries list at the top of the sidebar improves the user workflow by providing more immediate access.
The view hook for rendering the template sections was changed from `:view_issues_sidebar_planning_bottom` to `:view_issues_sidebar_queries_bottom`.
This relocates the "Issue template" and "Template for note" sections to appear directly below the "Custom queries" section, as shown below.
**Before:**
**After:**

Display custom queries above issue templates in sidebar

---

app/controllers/global_issue_templates_controller.rb
init.rb
spec/factories/members.rb
spec/factories/role.rb
spec/requests/global_issue_templates_spec.rb
spec/requests/issue_templates_spec.rb
spec/spec_helper.rb

- Lock down `global_issue_templates#orphaned_templates`, which lives under the global admin area, so only admins can reach it as originally intended
- Limit `issue_templates#load_selectable_fields` to the edit permission, since that selector is only surfaced while editing templates
- Added request specs
- orphaned templates 
- selectable fields endpoints
Other failing tests are being fixed in a separate PR.
https://github.com/agileware-jp/redmine_issue_templates/pull/140

 Restrict orphaned template access to admins and align permissions.
